export default [
  { name: 'corona', rank: 2 },
  { name: 'covid', rank: 2 },
  { name: 'curado', rank: 10 },
  { name: 'cura', rank: 10 },
  { name: 'curada', rank: 7 },
  { name: 'diminui', rank: 7 },
  { name: 'diminuindo', rank: 7 },
  { name: 'diminuiu', rank: 7 },
  { name: 'morreu', rank: -5 },
  { name: 'morreram', rank: -5 },
  { name: 'morte', rank: -5 },
  { name: 'infectado', rank: -1 },
  { name: 'promissor', rank: 8 },
  { name: 'resultado', rank: 8 },
  { name: 'vacina', rank: 8 },
  { name: 'recebe alta', rank: 8 },
  { name: 'cientista', rank: 10 },
  { name: 'menor número', rank: 10 },
  { name: 'teste', rank: 10 },
  { name: 'reduz caso', rank: 10 },
  { name: 'caixão', rank: -5 },
  { name: 'caixões', rank: -5 },
  { name: 'enterro', rank: -5 },
  { name: 'eleva caso', rank: -5 },
  { name: 'morre', rank: -5 }
];
