export default {

  'pt-br': [
    { name: 'corona', rank: 2 },
    { name: 'covid', rank: 2 },
    { name: 'curado', rank: 10 },
    { name: 'vence', rank: 10 },
    { name: 'cura', rank: 5 },
    { name: 'curada', rank: 7 },
    { name: 'diminui', rank: 7 },
    { name: 'diminuindo', rank: 7 },
    { name: 'diminuiu', rank: 7 },
    { name: 'morreu', rank: -5 },
    { name: 'morreram', rank: -5 },
    { name: 'morte', rank: -5 },
    { name: 'morto', rank: -5 },
    { name: 'óbito', rank: -5 },
    { name: 'infectado', rank: -1 },
    { name: 'promissor', rank: 8 },
    { name: 'resultado', rank: 8 },
    { name: 'vacina', rank: 8 },
    { name: 'recebe alta', rank: 10 },
    { name: 'cientista', rank: 5 },
    { name: 'menor número', rank: 10 },
    { name: 'teste', rank: 5 },
    { name: 'combate', rank: 5 },
    { name: 'trump', rank: -5 },
    { name: 'bolsonaro', rank: -5 },
    { name: 'suicídio', rank: -5 },
    { name: 'reduz caso', rank: 10 },
    { name: 'caixão', rank: -5 },
    { name: 'caixões', rank: -5 },
    { name: 'enterro', rank: -5 },
    { name: 'eleva caso', rank: -5 },
    { name: 'morre', rank: -5 },
    { name: 'suicida', rank: -5 },
    { name: 'suicidou', rank: -5 }
  ],
  'en-us': [
    { name: 'corona', rank: 2 },
    { name: 'covid', rank: 2 },
    { name: 'records', rank: 5 },
    { name: 'beats', rank: 10 },
    { name: 'heal', rank: 10 },
    { name: 'lockdown', rank: 2 },
    { name: 'good news', rank: 10 },
    { name: 'success', rank: 10 },
    { name: 'elimnate', rank: 10 },
    { name: 'dead', rank: -10 },
    { name: 'death', rank: -10 },
    { name: 'vaccine', rank: 8 },
    { name: 'flatten', rank: 8 },
    { name: 'recover', rank: 10 },
    { name: 'test', rank: 5 },
    { name: 'can\'t', rank: -5 },
    { name: 'trump', rank: -5 },
    { name: 'can not', rank: -5 },
    { name: 'kill', rank: -5 },
    { name: 'progressive', rank: 9 },
    { name: 'control', rank: 9 },
    { name: 'died', rank: -5 },
    { name: 'dies', rank: -5 },
    { name: 'suicide', rank: -5 }
  ]
};
